export const GameStates = {
	WHITE_PLAYER_SET_STONE: 'WHITE_PLAYER_SET_STONE',
	BLACK_PLAYER_SET_STONE: 'BLACK_PLAYER_SET_STONE',
	BLACK_PLAYER_SET_GOLDEN_STONE: 'BLACK_PLAYER_SET_GOLDEN_STONE',
	WHITE_PLAYER_MAKE_TURN: 'WHITE_PLAYER_MAKE_TURN',
	BLACK_PLAYER_MAKE_TURN: 'BLACK_PLAYER_MAKE_TURN',
}

export const Player = {
	WHITE: 'WHITE',
	BLACK: 'BLACK',
	GOLD: 'GOLD',
}